Backend: Vitis
ClockPeriod: 5
ClockUncertainty: 27%
HLSConfig:
  LayerName:
    dense:
      Precision:
        accum: auto
        bias: auto
        result: auto
        weight: auto
      ReuseFactor: 512
      Trace: false
    dense_1:
      Precision:
        accum: auto
        bias: auto
        result: auto
        weight: auto
      ReuseFactor: 512
      Trace: false
    dense_relu:
      Precision:
        result: auto
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 512
      TableSize: 1024
      Trace: false
    dropout:
      Precision:
        result: auto
        table: fixed<18,8,TRN,WRAP,0>
      ReuseFactor: 512
      TableSize: 1024
      Trace: false
    flatten:
      Precision:
        result: auto
      Trace: false
    input_layer:
      Precision:
        result: auto
      Trace: false
  Model:
    BitExact: null
    BramFactor: 1000000000
    Precision:
      default: fixed<16,6>
    ReuseFactor: 1
    Strategy: Resource
    TraceOutput: false
IOType: io_parallel
InputData: null
InputShapes:
  input_layer:
  - 28
  - 28
KerasModel: !keras_model 'mnist_hls_resource_approx_pot_test/keras_model.keras'
OutputDir: mnist_hls_resource_approx_pot_test
OutputPredictions: null
OutputShapes:
  layer6_out:
  - 10
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: 05e70d8b
Version: 1.0.0
WriterConfig:
  Namespace: null
  TBOutputStream: both
  WriteEmulationConstants: false
  WriteTar: false
  WriteWeightsTxt: true
